site_name: Janus Chung Homepage
theme:
  name: material
  icon:
    logo: material/alpha-j-box
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins: 
  - blog
  - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg



extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/janus/
    - icon: fontawesome/brands/github
      link: https://github.com/januschung

extra_css:
  - styles/extra.css
